### ISSUE TITLE
is there a pytorch  implementation?

### ISSUE THREAD

**Issue by a13668349935** [jyhjinghwang/SegSort#2]

**Comment by jyhjinghwang** [comment]
Hi,
Thanks for your interest in our work!

Unfortunately, our Pytorch reimplementation is not ready to release.
From our experience, it should be relatively easy to do it by changing the functions of "tf" to "torch" in the SegSort module and planting it on top of an existing PyTorch segmentation codebase.

Hope this helps.  Let me know if you have further questions; otherwise I'll close this issue for now.

Best,
Jyh-Jing
